# Generated by Django 2.1.5 on 2020-01-30 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('request_data', models.TextField()),
                ('response_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response_formatter.Hub')),
            ],
        ),
        migrations.CreateModel(
            name='RequestMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'Get Method'), ('POST', 'Post Method'), ('PUT', 'Put Method'), ('DELETE', 'Delete Method')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response_formatter.HubGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseHeaderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(choices=[('Response 200 (application/json)', 'Response 200 (application/json)')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='request_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response_formatter.RequestMethod'),
        ),
        migrations.AddField(
            model_name='action',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response_formatter.Resource'),
        ),
        migrations.AddField(
            model_name='action',
            name='response_header_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response_formatter.ResponseHeaderStatus'),
        ),
    ]
