# Generated by Django 2.1.5 on 2020-01-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_formatter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='url',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='hub',
            name='name',
            field=models.CharField(choices=[('workload', 'Workload'), ('hub', 'Hub'), ('logistics', 'Logistics')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='requestmethod',
            name='method',
            field=models.CharField(choices=[('GET', 'Get Method'), ('POST', 'Post Method'), ('PUT', 'Put Method'), ('DELETE', 'Delete Method')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='responseheaderstatus',
            name='header',
            field=models.CharField(choices=[('Response 200 (application/json)', 'Response 200 (application/json)')], max_length=200, unique=True),
        ),
    ]
