# Generated by Django 2.1.5 on 2020-01-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response_formatter', '0002_auto_20200130_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHeaderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(choices=[('Request (application/json)', 'Request (application/json)')], max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='request_header_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='response_formatter.RequestHeaderStatus'),
            preserve_default=False,
        ),
    ]
